import math
from typing import Optional

from .base import Bracket, FormatStrategy, MatchPlan

Pairing = tuple[int, Optional[int]]  # (player, opponent or None for a bye)


def total_rounds(participant_count: int) -> int:
    """Standard swiss length: ceil(log2(n)) rounds (at least 1)."""
    return max(1, math.ceil(math.log2(participant_count)))


def first_round_pairings(ordered_ids: list[int]) -> list[Pairing]:
    """Round 1 by the fold method: top half vs bottom half by seed.

    With an odd count the lowest seed receives a bye.
    """
    n = len(ordered_ids)
    half = n // 2
    pairs: list[Pairing] = [
        (ordered_ids[i], ordered_ids[half + i]) for i in range(half)
    ]
    if n % 2 == 1:
        pairs.append((ordered_ids[-1], None))
    return pairs


class SwissFormat(FormatStrategy):
    """Swiss: a fixed number of rounds, pairing players with similar records
    each round while avoiding rematches.

    Only round 1 is built up front (``build``); later rounds are generated by
    the service once the previous round finishes, via ``next_round_pairings``.
    """

    def build(self, participant_ids: list[int]) -> list[MatchPlan]:
        if len(participant_ids) < 2:
            raise ValueError("Swiss needs at least 2 participants.")
        return [
            MatchPlan(
                index=i,
                round_number=1,
                player_a=a,
                player_b=b,
                bracket=Bracket.SWISS,
            )
            for i, (a, b) in enumerate(first_round_pairings(participant_ids))
        ]

    def next_round_pairings(
        self,
        ordered_ids: list[int],
        played_pairs: set[frozenset],
        byes_had: set[int],
    ) -> list[Pairing]:
        """Pair the next round. ``ordered_ids`` must be sorted by standing
        (strongest first). Falls back to a sequential pairing if no rematch-free
        pairing exists."""
        players = list(ordered_ids)
        pairs: list[Pairing] = []

        if len(players) % 2 == 1:
            bye = _pick_bye(players, byes_had)
            players.remove(bye)
            pairs.append((bye, None))

        matched = _pair_without_rematches(players, played_pairs)
        if matched is None:
            matched = [(players[i], players[i + 1]) for i in range(0, len(players), 2)]
        return pairs + matched


def _pick_bye(players: list[int], byes_had: set[int]) -> int:
    """Lowest-ranked player who hasn't had a bye yet (else the lowest)."""
    for candidate in reversed(players):
        if candidate not in byes_had:
            return candidate
    return players[-1]


def _pair_without_rematches(
    players: list[int], played_pairs: set[frozenset]
) -> Optional[list[Pairing]]:
    if not players:
        return []
    first = players[0]
    for i in range(1, len(players)):
        opponent = players[i]
        if frozenset((first, opponent)) in played_pairs:
            continue
        rest = players[1:i] + players[i + 1 :]
        sub = _pair_without_rematches(rest, played_pairs)
        if sub is not None:
            return [(first, opponent)] + sub
    return None
